# Generated by Django 6.0.3 on 2026-04-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuer', models.CharField(max_length=255)),
                ('network', models.CharField(max_length=255)),
                ('card_type', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('annual_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_reward_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signup_bonus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('signup_bonus_required_spending', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reward_Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('reward_unit', models.CharField(max_length=255)),
                ('reward_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_rules', to='cards.card_products')),
            ],
            options={
                'unique_together': {('card_product', 'category')},
            },
        ),
    ]
