# Generated by Django 6.0.3 on 2026-06-24 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card_products',
            unique_together={('name', 'issuer')},
        ),
    ]
