# Generated by Django 6.0.3 on 2026-08-04 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_card_products_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_products',
            name='is_catalog',
            field=models.BooleanField(default=True),
        ),
    ]
