# Generated by Django 6.0.3 on 2026-08-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_card_products_is_catalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_products',
            name='signup_bonus_spend_period_months',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
