# Generated by Django 6.0.3 on 2026-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_products_signup_bonus_spend_period_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_products',
            name='reward_currency',
            field=models.CharField(default='cash_back', max_length=32),
        ),
    ]
