# Generated by Django 6.0.3 on 2026-04-14 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('uploads', '0001_initial'),
        ('users', '0002_user_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCC_Codes',
            fields=[
                ('code', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=255)),
                ('row_index', models.PositiveIntegerField()),
                ('mcc_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mcc_code_transactions', to='transactions.mcc_codes')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_transactions', to='uploads.uploads')),
                ('user_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_card_transactions', to='users.user_cards')),
            ],
            options={
                'unique_together': {('upload', 'row_index')},
            },
        ),
    ]
