# Generated by Django 6.0.3 on 2026-04-14 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcc_codes',
            name='merchant_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
