# Generated by Django 6.0.3 on 2026-04-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_mcc_codes_merchant_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcc_codes',
            name='title',
        ),
    ]
