# Generated by Django 6.0.3 on 2026-07-21 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_mcc_codes_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='mcc_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mcc_code_transactions', to='transactions.mcc_codes'),
        ),
    ]
