# Generated by Django 6.0.3 on 2026-07-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transactions_mcc_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantResolution',
            fields=[
                ('merchant_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, default='', max_length=32)),
                ('source', models.CharField(max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mcc_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='transactions.mcc_codes')),
            ],
        ),
    ]
