# Generated by Django 6.0.3 on 2026-08-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_merchantresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='external_id',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transactions',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
