# Generated by Django 6.0.3 on 2026-08-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_plaid_and_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantresolution',
            name='mcc_code',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='mcc_code',
        ),
        migrations.AddField(
            model_name='transactions',
            name='category',
            field=models.CharField(default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='merchantresolution',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='merchantresolution',
            name='confidence',
            field=models.FloatField(default=1.0),
        ),
        migrations.DeleteModel(
            name='MCC_Codes',
        ),
    ]
