# Generated by Django 6.0.3 on 2026-08-03 23:36

import re as _re

from django.db import migrations, models

# ── inline renormalization helpers ────────────────────────────────────────
# Inlined (not imported from services/) so the migration remains correct
# regardless of future application code changes.

_PROCESSOR_PREFIXES = frozenset(["SQ", "PAYPAL", "TST", "SP", "VENMO", "ETSY"])
_MAX_KEY = 255


def _mk(desc):
    if not isinstance(desc, str) or not desc:
        return ""
    t = desc.upper()
    if "*" in t:
        left, right = t.split("*", 1)
        left, right = left.strip(), right.strip()
        if len(right) == 1:
            t = left + right
        elif left in _PROCESSOR_PREFIXES:
            t = right
        else:
            t = left
    if "#" in t:
        t = t.split("#", 1)[0]
    t = _re.sub(r"\b[A-Z]\d+\b", " ", t)
    t = _re.sub(r"\d+", "", t)
    t = t.replace("'", "").replace("\u2019", "")
    t = _re.sub(r"[^A-Z]+", " ", t)
    return " ".join(t.split())[:_MAX_KEY]


def _renormalize_existing_transactions(apps, schema_editor):
    """
    Re-key every existing transaction with the corrected normalizer.

    The old algorithm cut on '*' before checking for processor prefixes, so
    "PAYPAL *NETFLIX" → "PAYPAL" instead of "NETFLIX". Any MerchantResolution
    rows keyed to the old values will no longer match; the user will need to
    re-answer those in the review queue or re-upload their statement.
    """
    Transactions = apps.get_model("transactions", "Transactions")
    MerchantResolution = apps.get_model("transactions", "MerchantResolution")

    batch = []
    for tx in Transactions.objects.all():
        new_key = _mk(tx.description)
        if new_key != tx.merchant_key or tx.normalized_description == "":
            tx.merchant_key = new_key
            tx.normalized_description = new_key.title()
            batch.append(tx)

    if batch:
        Transactions.objects.bulk_update(
            batch, ["merchant_key", "normalized_description"], batch_size=500
        )

    # Clear MerchantResolution rows that were keyed to processor names (e.g.
    # "PAYPAL") — those keys no longer exist after the rekey above.
    MerchantResolution.objects.filter(merchant_key__in=set(_PROCESSOR_PREFIXES)).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_user_scoped_resolutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalMerchantAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('canonical_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': 'global merchant aliases',
            },
        ),
        migrations.AddField(
            model_name='transactions',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='transactions',
            name='normalized_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='transactions',
            name='resolution_source',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.RunPython(
            _renormalize_existing_transactions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
